criso_colla_theme_home:
    pattern: /
    defaults: { _controller: CrisoCollaThemeBundle:Theme:renderPath }
    requirements:
        path: ".+"

criso_colla_theme_render_path:
    pattern: /{path}
    defaults: { _controller: CrisoCollaThemeBundle:Theme:renderPath }
    requirements:
        path: ".+"

