<?php

namespace CrisoColla\ThemeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Content2RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Content2RegionRepository extends EntityRepository
{
}
