<?php

namespace CrisoColla\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Content2TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Content2TypeRepository extends EntityRepository
{
}
