<?php

namespace CrisoColla\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubContentRepository extends EntityRepository
{
}
