parameters:
#    criso_colla_test.example.class: CrisoColla\TestBundle\Example

services:
#    criso_colla_test.example:
#        class: %criso_colla_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
