parameters:
#    criso_colla_content.example.class: CrisoColla\ContentBundle\Example

services:
#    criso_colla_content.example:
#        class: %criso_colla_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    criso_colla_content.twig.content_extension:
        class: CrisoColla\ContentBundle\Twig\ContentExtension
        arguments: [@translator]
        tags:
            - { name: twig.extension }

    criso_colla_content.graph_service:
        class: CrisoColla\ContentBundle\Services\GraphService
        arguments: []
