parameters:
#    criso_colla_content.example.class: CrisoColla\ContentBundle\Example

services:
#    criso_colla_content.example:
#        class: %criso_colla_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
